### ISSUE TITLE
[refactor] upgrade node version in Dockerfile

### ISSUE THREAD

**Issue by BlackHole1** [netless-io/flat-server#352]
file: `Dockerfile`

current Node version: `node:12.22`
Alternative upgrades: ~`node:16.4.0`~ `node:16.3.0`

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by BlackHole1** [comment]
> I would like to take this one.

That's great

**Comment by BlackHole1** [comment]
This is my mistake, nodejs is not currently uploaded at hub.docker version `16.14.0`
