### ISSUE TITLE
mysql table information

### ISSUE THREAD

**Issue by sunshinehome** [netless-io/flat-server#531]
The database and related table information were not found

**Comment by BlackHole1** [comment]
Here: https://github.com/netless-io/flat-server/tree/main/src/model

**Comment by BlackHole1** [comment]
You can change here: https://github.com/netless-io/flat-server/blob/254f2345daaa6a22f00d9df1bdb43a97c669c217/src/thirdPartyService/TypeORMService.ts#L50

add `synchronize: true`. See:
