### ISSUE TITLE
数据库脚本在哪里？

### ISSUE THREAD

**Issue by Ken-LK** [netless-io/flat-server#715]
数据库脚本在哪里？

**Comment by hyrious** [comment]
数据库描述通过 ORM 实现，参考 [prepare-test-env.sh](https://github.com/netless-io/flat-server/blob/main/scripts/prepare-test-env.sh) 准备好数据库连接后，执行 [`npm run test:sync:orm`](https://github.com/netless-io/flat-server/blob/main/package.json#L9) 就可以生成所有表。

**Comment by 414726193** [comment]
> 数据库脚本在哪里？

您好我可以加您微信吗，有问题想请教您
