### ISSUE TITLE
这个最终的服务端还是没有开源，还是最终调用声网api吧？

### ISSUE THREAD

**Issue by andotorg** [netless-io/flat-server#718]
这个最终的服务端还是没有开源，还是最终调用声网api吧？

**Comment by syt-honey** [comment]
> 这个最终的服务端还是没有开源，还是最终调用声网api吧？

是的，底层 SDK 是闭源的

**Comment by leavesster** [comment]
看你怎么定义最终的服务端。flat-server 作为 flat 网站和服务的后端 API 是完整开源。他依赖的其他服务，并不开源。
