### ISSUE TITLE
Hello, may I ask where the database script is located? How can I initialize the database?

### ISSUE THREAD

**Issue by liyuhang** [netless-io/flat-server#796]
Hello, may I ask where the database script is located? How can I initialize the database?

**Comment by hyrious** [comment]
If you have docker installed, you can run https://github.com/netless-io/flat-server/blob/main/scripts/prepare-test-env.sh to prepare mysql and redis databases. Then run [`yarn run test:sync:orm`](https://github.com/netless-io/flat-server/blob/c5fd4dc759fb46cf315e308a9885eb6fd4f462b2/package.json#L9) to create tables in those databases.

**Comment by liyuhang** [comment]
The issue has been resolved. Thank you.
