### ISSUE TITLE
大班课能够实现全部人员语音开放吗？

### ISSUE THREAD

**Issue by wang3680** [netless-io/flat-server#800]
大班课能够实现全部人员语音开放吗？

**Comment by hyrious** [comment]
目前上台人数有限制 (详见 #801)，而只有上台了才能打开麦克风，所以短期内没有实现这个需求的想法。

你说的全员开启麦克风的场景适用于大型会议场景，为了避免客户端解码开销过大，可以使用 Agora RTC 的[音强选流](https://doc.shengwang.cn/doc/rtc/javascript/advanced-features/audio-stream-filter)功能，详见文档。

如果你对上面提到的技术有兴趣，可以自行研究。更多有关 Flat 的功能讨论建议反馈给 @Leooeloel: https://www.yuque.com/leooel/ec1kmm/vmsolg
