### ISSUE TITLE
小班课怎么能够开放人数限制？？

### ISSUE THREAD

**Issue by wang3680** [netless-io/flat-server#801]
小班课怎么能够开放人数限制？？

**Comment by hyrious** [comment]
目前定的小班课人数上限 16（上台数）主要来自于 Agora RTC (音视频推流服务) [最多只支持 17 人同时发流](https://doc.shengwang.cn/doc/rtc/javascript/best-practice/multi-user-video#3-%E5%8F%91%E5%B8%83%E5%92%8C%E8%AE%A2%E9%98%85%E6%B5%81) (老师始终在台上)。

如果要允许更多人进入房间，目前小班课已经支持 (只是超过的观众不会自动上台)。

如果要允许更多人上台发流，业内有几种方案：

- 一个房间不止对应一个频道，而是对应多个频道，通过[跨频道媒体流转发](https://doc.shengwang.cn/doc/rtc/javascript/advanced-features/media-relay)实现多路视频，缺点是容易打到客户端性能上限；
- 增设中间服务器合并视频流，类似腾讯的元宇宙会议场景，此方法需要额外部署计算节点，我们目前资源有限无法实现。

如果你对上面提到的技术有兴趣，可以自行研究。更多有关 Flat 的功能讨论建议反馈给 @Leooeloel: https://www.yuque.com/leooel/ec1kmm/vmsolg
